import Link from "next/link";
import { ArrowRight, Megaphone } from "lucide-react";
import { CompanyNav } from "@/components/brand";
import { CampaignForm } from "@/components/campaign-form";
import { api, Campaign } from "@/lib/api";

export const dynamic = "force-dynamic";

export default async function CampaignsPage() {
  const campaigns = await api<Campaign[]>("/api/campaigns").catch(() => []);
  return <main className="min-h-screen"><CompanyNav /><section className="mx-auto max-w-[1240px] px-5 pb-20 pt-12 lg:px-9"><div className="flex flex-col justify-between gap-6 border-b hairline pb-8 sm:flex-row sm:items-end"><div><div className="text-[10px] font-black uppercase tracking-[.15em] text-[#85887f]">Growth portfolio</div><h1 className="display mt-3 text-5xl font-bold">Campaigns</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#6e7169]">Every card ties a Pioneer decision to real Terac labor, human preference, referral traffic, Stripe revenue, and contribution.</p></div><CampaignForm /></div><div className="mt-8 grid gap-4 md:grid-cols-2">{campaigns.map((campaign) => <Link key={campaign.id} href={`/company/campaigns/${campaign.id}`} className="group rounded-[24px] border hairline bg-white/70 p-6 transition hover:-translate-y-1 hover:shadow-xl"><div className="flex items-center justify-between"><span className="rounded-full bg-[#eceee6] px-2.5 py-1 text-[9px] font-black uppercase tracking-wider text-[#69705c]">{campaign.status.replaceAll("_", " ")}</span><ArrowRight size={17} className="transition group-hover:translate-x-1" /></div><h2 className="display mt-5 text-2xl font-bold">{campaign.name}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-[#696d64]">{campaign.objective}</p><div className="mt-6 grid grid-cols-3 border-t hairline pt-4 text-xs"><div><span className="block text-[9px] uppercase tracking-wider text-[#93968e]">Visits</span><strong className="mt-1 block text-lg">{campaign.performance.visits ?? 0}</strong></div><div><span className="block text-[9px] uppercase tracking-wider text-[#93968e]">Support</span><strong className="mt-1 block text-lg">{campaign.performance.stripe_conversions ?? 0}</strong></div><div><span className="block text-[9px] uppercase tracking-wider text-[#93968e]">Revenue</span><strong className="mt-1 block text-lg">${Number(campaign.performance.revenue ?? 0).toFixed(2)}</strong></div></div></Link>)}{!campaigns.length && <div className="col-span-full grid min-h-80 place-items-center rounded-[26px] border border-dashed border-black/15 text-center"><div><Megaphone className="mx-auto text-[#a8aca2]" /><h2 className="display mt-4 text-2xl font-bold">No campaigns yet</h2><p className="mt-2 text-sm text-[#7a7d75]">Run Pioneer, then create the first real campaign. No demo rows are fabricated.</p></div></div>}</div></section></main>;
}
