"use client";

import { Plus, X, Loader2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { API_URL } from "@/lib/api";

export function CampaignForm() {
  const router = useRouter(); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState({ name: "Before / After v1", objective: "Drive qualified visits and voluntary $5 support for open-source ReproClip.", audience: "Indie hackers, startup founders, and developer-tool teams", creative_style: "before_after_demo", hook: "Your screen recording isn't the demo.", platforms: ["x", "linkedin"], budget_usd: 20 });
  const submit = async () => {
    const token = sessionStorage.getItem("reproclip_founder_token") || window.prompt("Enter the founder approval token:") || ""; if (!token) return;
    sessionStorage.setItem("reproclip_founder_token", token); setBusy(true); setError("");
    const response = await fetch(`${API_URL}/api/campaigns`, { method: "POST", headers: { "Content-Type": "application/json", "X-Founder-Token": token }, body: JSON.stringify(form) });
    const body = await response.json().catch(() => ({})); setBusy(false);
    if (!response.ok) { setError(body.detail || "Campaign creation failed"); return; }
    setOpen(false); router.push(`/company/campaigns/${body.id}`); router.refresh();
  };
  return <>{<button onClick={() => setOpen(true)} className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#171916] px-5 text-xs font-black text-white"><span className="grid size-5 place-items-center rounded-md bg-[#d8ff57] text-black"><Plus size={13} /></span> New campaign</button>}{open && <div className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4 backdrop-blur-sm"><div className="max-h-[calc(100vh-32px)] w-full max-w-xl overflow-y-auto rounded-[26px] bg-[#f8f8f3] shadow-2xl"><div className="flex items-start justify-between border-b hairline p-6"><div><h2 className="display text-2xl font-bold">Commission a campaign</h2><p className="mt-1 text-xs text-[#74776e]">The brief incorporates the latest Pioneer decision when one exists.</p></div><button onClick={() => setOpen(false)} className="grid size-8 place-items-center rounded-lg hover:bg-black/5"><X size={17} /></button></div><div className="space-y-4 p-6">{(["name", "objective", "audience", "hook"] as const).map((key) => <label key={key} className="block"><span className="text-xs font-bold capitalize">{key.replace("_", " ")}</span>{key === "objective" ? <textarea rows={3} value={form[key]} onChange={(e) => setForm((v) => ({ ...v, [key]: e.target.value }))} className="mt-2 w-full rounded-xl border border-black/12 bg-white p-3 text-sm outline-none focus:border-[#91b800]" /> : <input value={form[key]} onChange={(e) => setForm((v) => ({ ...v, [key]: e.target.value }))} className="mt-2 h-11 w-full rounded-xl border border-black/12 bg-white px-3 text-sm outline-none focus:border-[#91b800]" />}</label>)}<div className="grid grid-cols-2 gap-3"><label><span className="text-xs font-bold">Creative style</span><select value={form.creative_style} onChange={(e) => setForm((v) => ({ ...v, creative_style: e.target.value }))} className="mt-2 h-11 w-full rounded-xl border border-black/12 bg-white px-3 text-sm"><option value="before_after_demo">Before / after demo</option><option value="feature_tour">Feature tour</option><option value="talking_head">Talking head</option></select></label><label><span className="text-xs font-bold">Terac budget</span><input type="number" min="0" step="1" value={form.budget_usd} onChange={(e) => setForm((v) => ({ ...v, budget_usd: Number(e.target.value) }))} className="mt-2 h-11 w-full rounded-xl border border-black/12 bg-white px-3 text-sm" /></label></div>{error && <p className="rounded-xl bg-[#fff0ed] p-3 text-xs text-[#923e36]">{error}</p>}<button onClick={() => void submit()} disabled={busy} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#d8ff57] text-xs font-black disabled:opacity-50">{busy && <Loader2 size={15} className="animate-spin" />} Create persisted campaign</button></div></div></div>}</>;
}
