import Link from "next/link";
import { ArrowLeft, FlaskConical, Link2, ShieldAlert, Users } from "lucide-react";
import { notFound } from "next/navigation";
import { CompanyNav } from "@/components/brand";
import { FounderAction } from "@/components/founder-action";
import { api, Campaign } from "@/lib/api";

export const dynamic = "force-dynamic";

export default async function CampaignPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const campaign = await api<Campaign>(`/api/campaigns/${id}`).catch(() => null); if (!campaign) notFound();
  const creators = campaign.creators || []; const studies = campaign.studies || []; const creatives = campaign.creatives || [];
  return <main className="min-h-screen"><CompanyNav /><section className="mx-auto max-w-[1320px] px-5 pb-20 pt-9 lg:px-9"><Link href="/company/campaigns" className="inline-flex items-center gap-2 text-xs font-bold text-[#74776e]"><ArrowLeft size={14} /> Campaigns</Link><div className="mt-6 grid gap-8 border-b hairline pb-9 lg:grid-cols-[1fr_340px]"><div><div className="flex items-center gap-2"><span className="rounded-full bg-[#e9ede0] px-2.5 py-1 text-[9px] font-black uppercase tracking-wider">{campaign.status.replaceAll("_", " ")}</span>{campaign.current_decision && <span className="rounded-full bg-[#171916] px-2.5 py-1 text-[9px] font-black uppercase tracking-wider text-[#d8ff57]">CEO: {campaign.current_decision.replaceAll("_", " ")}</span>}</div><h1 className="display mt-4 text-[clamp(40px,5vw,68px)] font-bold leading-none">{campaign.name}</h1><p className="mt-5 max-w-3xl text-[16px] leading-7 text-[#676b62]">{campaign.objective}</p></div><div className="rounded-2xl border hairline bg-white/65 p-5"><div className="text-[9px] font-black uppercase tracking-[.14em] text-[#8b8e86]">Campaign economics</div><div className="mt-4 grid grid-cols-2 gap-4 text-xs"><div><span className="text-[#898c84]">Revenue</span><strong className="display mt-1 block text-2xl">${Number(campaign.performance.revenue ?? 0).toFixed(2)}</strong></div><div><span className="text-[#898c84]">Terac cost</span><strong className="display mt-1 block text-2xl">${Number(campaign.performance.terac_cost ?? 0).toFixed(2)}</strong></div><div><span className="text-[#898c84]">Conversion</span><strong className="mt-1 block">{(Number(campaign.performance.conversion_rate ?? 0) * 100).toFixed(2)}%</strong></div><div><span className="text-[#898c84]">Contribution</span><strong className="mt-1 block">${Number(campaign.performance.gross_contribution ?? 0).toFixed(2)}</strong></div></div></div></div>

      <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-6"><section className="rounded-[24px] border hairline bg-white/65 p-6"><div className="text-[10px] font-black uppercase tracking-[.15em] text-[#85887f]">Terac creator brief</div><div className="mt-4 whitespace-pre-line text-sm leading-7 text-[#555951]">{campaign.brief}</div><div className="mt-5 flex flex-wrap gap-3"><FounderAction path={`/api/campaigns/${campaign.id}/launch-terac`} body={{ kind: "CREATOR", count: 3 }} label="Request 3 creators through Terac" /><FounderAction path={`/api/campaigns/${campaign.id}/launch-terac`} body={{ kind: "CREATIVE_TEST", count: 30 }} label="Request general-population test" className="border border-white/15" /></div></section>
        <section className="rounded-[24px] border hairline bg-white/65 p-6"><div className="flex items-center justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.15em] text-[#85887f]">Human preference</div><h2 className="display mt-2 text-2xl font-bold">Creative comparison</h2></div><FlaskConical size={20} /></div>{creatives.length ? <div className="mt-6 space-y-5">{creatives.map((creative: any) => { const value = creative.preference_score; return <div key={creative.id}><div className="flex items-end justify-between gap-3 text-xs"><div><strong>{creative.name}</strong><span className="ml-2 text-[#92958d]">{creative.response_count || 0} responses</span></div><span className="font-mono font-bold">{value == null ? "Awaiting Terac" : `${(value * 100).toFixed(0)}%`}</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-[#e6e8e0]"><div className="h-full rounded-full bg-[#b9e328]" style={{ width: `${value == null ? 0 : value * 100}%` }} /></div><div className="mt-2 flex gap-4 text-[9px] text-[#898c84]"><span>Clarity {creative.clarity_score == null ? "—" : `${(creative.clarity_score * 100).toFixed(0)}%`}</span><span>Click {creative.click_intent == null ? "—" : `${(creative.click_intent * 100).toFixed(0)}%`}</span><span>Support {creative.support_intent == null ? "—" : `${(creative.support_intent * 100).toFixed(0)}%`}</span></div></div>; })}</div> : <div className="mt-6 rounded-2xl bg-[#f0f0ea] p-6 text-center text-xs text-[#7c7f77]">Approved creator submissions become testable creatives. No placeholder scores are shown.</div>}</section>
        <section className="rounded-[24px] border hairline bg-white/65 p-6"><div className="flex items-center justify-between"><h2 className="display text-2xl font-bold">Human creators</h2><Users size={20} /></div>{creators.length ? <div className="mt-5 divide-y hairline">{creators.map((creator: any) => <div key={creator.id} className="py-5"><div className="flex items-center justify-between"><div><strong className="text-sm">{creator.display_name}</strong><p className="mt-1 font-mono text-[9px] text-[#8d9088]">{creator.terac_creator_id}</p></div><span className="rounded-full bg-[#eceee6] px-2 py-1 text-[8px] font-black uppercase tracking-wider">{creator.status}</span></div><div className="mt-4 grid grid-cols-4 gap-3 text-xs"><span>Visits <strong className="block">{creator.visits}</strong></span><span>Support <strong className="block">{creator.supporters}</strong></span><span>Revenue <strong className="block">${Number(creator.revenue).toFixed(2)}</strong></span><span>CVR <strong className="block">{(creator.conversion_rate * 100).toFixed(2)}%</strong></span></div><a href={creator.referral_url} className="mt-3 flex items-center gap-2 truncate font-mono text-[10px] text-[#668400]"><Link2 size={12} /> {creator.referral_url}</a>{creator.submissions?.map((submission: any) => <Link key={submission.id} href={`/company/submissions/${submission.id}`} className="mt-3 flex items-center justify-between rounded-xl border hairline bg-white p-3 text-xs font-bold"><span>Review submission</span><span className="text-[#7e8179]">{submission.status}</span></Link>)}</div>)}</div> : <div className="mt-5 rounded-2xl bg-[#f0f0ea] p-6 text-center text-xs text-[#7c7f77]">No creator records have been returned by Terac.</div>}</section></div>

        <aside className="space-y-4"><section className="rounded-[24px] bg-[#171916] p-5 text-white"><div className="flex items-center gap-2 text-sm font-bold"><ShieldAlert size={17} className="text-[#d8ff57]" /> Financial Human Approval Required</div><p className="mt-3 text-xs leading-5 text-white/50">AI may recommend. Only the founder approval screen can approve or reject a creator submission. ReproClip never auto-approves a Terac payout.</p></section><section className="rounded-[24px] border hairline bg-white/65 p-5"><div className="text-[10px] font-black uppercase tracking-[.14em] text-[#85887f]">Terac studies</div><div className="mt-4 space-y-3">{studies.map((study: any) => <div key={study.id} className="rounded-xl border hairline bg-white p-3"><div className="flex items-center justify-between"><strong className="text-xs">{study.kind.replaceAll("_", " ")}</strong><span className="text-[8px] font-black uppercase tracking-wider text-[#70746a]">{study.status}</span></div><div className="mt-2 font-mono text-[9px] leading-4 text-[#8b8e86]">{study.terac_opportunity_id || study.terac_request_id || "Awaiting remote ID"}</div>{study.terac_request_id && !study.terac_opportunity_id && <div className="mt-3"><FounderAction path={`/api/studies/${study.id}/launch`} label="Approve spend & launch" /></div>}{study.terac_opportunity_id && <div className="mt-3"><FounderAction path={`/api/studies/${study.id}/sync`} label="Sync real results" /></div>}</div>)}{!studies.length && <p className="text-xs leading-5 text-[#85887f]">No Terac request has been made.</p>}</div></section></aside></div>
    </section></main>;
}
