"""track surveyed humans per study

Revision ID: 1a81ff1d16b5
Revises: 53275bbeceaa
Create Date: 2026-08-15 12:26:24.167719
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1a81ff1d16b5'
down_revision: Union[str, Sequence[str], None] = '53275bbeceaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terac_studies', sa.Column('response_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terac_studies', 'response_count')
    # ### end Alembic commands ###
