"""initial autonomous company schema

Revision ID: 53275bbeceaa
Revises:
Create Date: 2026-08-15 12:11:27.109598
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '53275bbeceaa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ceo_actions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('decision', sa.String(length=60), nullable=False),
    sa.Column('target_audience', sa.String(length=240), nullable=False),
    sa.Column('creative_style', sa.String(length=80), nullable=False),
    sa.Column('platform_priority', sa.JSON(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=False),
    sa.Column('next_actions', sa.JSON(), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=40), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_statuses',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('social_posts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('creator_id', sa.String(length=40), nullable=True),
    sa.Column('campaign_id', sa.String(length=40), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('revenue_cents', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_posts_campaign_id'), 'social_posts', ['campaign_id'], unique=False)
    op.create_table('stripe_payments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=180), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=180), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('customer_email', sa.String(length=240), nullable=True),
    sa.Column('campaign_id', sa.String(length=40), nullable=True),
    sa.Column('creator_id', sa.String(length=40), nullable=True),
    sa.Column('referral_code', sa.String(length=24), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_intent_id'),
    sa.UniqueConstraint('stripe_session_id')
    )
    op.create_index(op.f('ix_stripe_payments_campaign_id'), 'stripe_payments', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_stripe_payments_creator_id'), 'stripe_payments', ['creator_id'], unique=False)
    op.create_index(op.f('ix_stripe_payments_referral_code'), 'stripe_payments', ['referral_code'], unique=False)
    op.create_table('visits',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('referral_code', sa.String(length=24), nullable=True),
    sa.Column('campaign_id', sa.String(length=40), nullable=True),
    sa.Column('creator_id', sa.String(length=40), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('visited_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_campaign_id'), 'visits', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_visits_creator_id'), 'visits', ['creator_id'], unique=False)
    op.create_index(op.f('ix_visits_referral_code'), 'visits', ['referral_code'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=240), nullable=False),
    sa.Column('creative_style', sa.String(length=80), nullable=False),
    sa.Column('hook', sa.String(length=240), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('budget_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('current_decision', sa.String(length=80), nullable=True),
    sa.Column('ceo_action_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ceo_action_id'], ['ceo_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creators',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('campaign_id', sa.String(length=40), nullable=False),
    sa.Column('terac_creator_id', sa.String(length=120), nullable=True),
    sa.Column('display_name', sa.String(length=140), nullable=False),
    sa.Column('referral_code', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reward_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creators_campaign_id'), 'creators', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_creators_referral_code'), 'creators', ['referral_code'], unique=True)
    op.create_table('terac_studies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('campaign_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('terac_request_id', sa.String(length=140), nullable=True),
    sa.Column('terac_opportunity_id', sa.String(length=140), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('brief', sa.JSON(), nullable=False),
    sa.Column('raw_result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terac_studies_campaign_id'), 'terac_studies', ['campaign_id'], unique=False)
    op.create_table('creator_submissions',
    sa.Column('id', sa.String(length=44), nullable=False),
    sa.Column('creator_id', sa.String(length=40), nullable=False),
    sa.Column('terac_submission_id', sa.String(length=140), nullable=True),
    sa.Column('asset_url', sa.Text(), nullable=False),
    sa.Column('social_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('automated_checks', sa.JSON(), nullable=False),
    sa.Column('ai_recommendation', sa.String(length=20), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_reason', sa.Text(), nullable=True),
    sa.Column('founder_approved', sa.Boolean(), nullable=True),
    sa.Column('founder_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('terac_submission_id')
    )
    op.create_index(op.f('ix_creator_submissions_creator_id'), 'creator_submissions', ['creator_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('campaign_id', sa.String(length=40), nullable=False),
    sa.Column('creator_id', sa.String(length=40), nullable=True),
    sa.Column('destination_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_campaign_id'), 'referrals', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_referrals_code'), 'referrals', ['code'], unique=True)
    op.create_index(op.f('ix_referrals_creator_id'), 'referrals', ['creator_id'], unique=False)
    op.create_table('creatives',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('campaign_id', sa.String(length=40), nullable=False),
    sa.Column('submission_id', sa.String(length=44), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('style', sa.String(length=80), nullable=False),
    sa.Column('asset_url', sa.Text(), nullable=False),
    sa.Column('clarity_score', sa.Float(), nullable=True),
    sa.Column('click_intent', sa.Float(), nullable=True),
    sa.Column('support_intent', sa.Float(), nullable=True),
    sa.Column('preference_score', sa.Float(), nullable=True),
    sa.Column('response_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['creator_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creatives_campaign_id'), 'creatives', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creatives_campaign_id'), table_name='creatives')
    op.drop_table('creatives')
    op.drop_index(op.f('ix_referrals_creator_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_code'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_campaign_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_creator_submissions_creator_id'), table_name='creator_submissions')
    op.drop_table('creator_submissions')
    op.drop_index(op.f('ix_terac_studies_campaign_id'), table_name='terac_studies')
    op.drop_table('terac_studies')
    op.drop_index(op.f('ix_creators_referral_code'), table_name='creators')
    op.drop_index(op.f('ix_creators_campaign_id'), table_name='creators')
    op.drop_table('creators')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_visits_referral_code'), table_name='visits')
    op.drop_index(op.f('ix_visits_creator_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_campaign_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_stripe_payments_referral_code'), table_name='stripe_payments')
    op.drop_index(op.f('ix_stripe_payments_creator_id'), table_name='stripe_payments')
    op.drop_index(op.f('ix_stripe_payments_campaign_id'), table_name='stripe_payments')
    op.drop_table('stripe_payments')
    op.drop_index(op.f('ix_social_posts_campaign_id'), table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_table('integration_statuses')
    op.drop_table('company_events')
    op.drop_table('ceo_actions')
    # ### end Alembic commands ###
