import { AlertCircle, Banknote, ReceiptText } from "lucide-react";
import { CompanyNav } from "@/components/brand";
import { api, Metrics } from "@/lib/api";

export const dynamic = "force-dynamic";

export default async function FinancialsPage() {
  const data = await api<{ metrics: Metrics }>("/api/company/metrics").catch(() => null); const m = data?.metrics;
  const rows = [{ label: "Stripe support", value: m?.revenue ?? 0, kind: "revenue" }, { label: "Terac creators + testing", value: m?.terac_spend ?? 0, kind: "cost" }, { label: "Infrastructure", value: m?.infrastructure_cost, kind: "cost" }];
  return <main className="min-h-screen"><CompanyNav /><section className="mx-auto max-w-[1000px] px-5 pb-20 pt-12 lg:px-9"><div className="border-b hairline pb-8"><div className="text-[10px] font-black uppercase tracking-[.15em] text-[#85887f]">Autonomous company P&amp;L</div><h1 className="display mt-3 text-5xl font-bold">Every dollar is real.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[#6f726a]">Webhook-verified Stripe payments minus recorded Terac costs. Missing infrastructure data stays unavailable; the dashboard never estimates it.</p></div><div className="mt-8 grid gap-5 md:grid-cols-[1fr_320px]"><div className="rounded-[26px] border hairline bg-white/70 p-6"><div className="flex items-center gap-2 text-sm font-bold"><ReceiptText size={18} /> Profit &amp; loss</div><div className="mt-6 divide-y hairline">{rows.map((row) => <div key={row.label} className="flex items-center justify-between py-5"><span className="text-sm text-[#676a63]">{row.label}</span><strong className={`tabular text-lg ${row.value == null ? "text-[#999c94]" : row.kind === "cost" ? "text-[#9e4a41]" : "text-[#5d7d00]"}`}>{row.value == null ? "Unavailable" : `${row.kind === "cost" ? "−" : "+"}$${Number(row.value).toFixed(2)}`}</strong></div>)}<div className="flex items-center justify-between py-6"><strong>Gross contribution</strong><strong className="display tabular text-3xl">{m?.gross_contribution == null ? "Unavailable" : `$${m.gross_contribution.toFixed(2)}`}</strong></div></div></div><aside className="space-y-4"><div className="rounded-[24px] bg-[#171916] p-6 text-white"><Banknote className="text-[#d8ff57]" /><div className="mt-5 text-[10px] font-black uppercase tracking-[.14em] text-white/40">Unit economics</div><div className="mt-4 grid grid-cols-2 gap-5"><div><span className="text-xs text-white/45">ROAS</span><strong className="display mt-1 block text-2xl">{m?.roas == null ? "—" : `${m.roas}×`}</strong></div><div><span className="text-xs text-white/45">CAC</span><strong className="display mt-1 block text-2xl">{m?.cac == null ? "—" : `$${m.cac}`}</strong></div></div></div><div className="flex gap-3 rounded-[20px] border hairline bg-white/70 p-4 text-xs leading-5 text-[#71746c]"><AlertCircle size={17} className="shrink-0" />ROAS and CAC appear only when both real Terac cost and Stripe conversions exist.</div></aside></div></section></main>;
}
